name: Build examples IDF5.0
on:
  workflow_dispatch:

jobs:
  Build-examples:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: examples/factory_demo
      BIN_FILE: ESP-Box_Demo_V0.3.1.bin
    container: espressif/idf:release-v5.0
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: esp-idf build
      run: |
        pwd
        ls -al
        cd /opt/esp/idf
        git checkout 94d9c529f3
        git submodule update --init --recursive
        tools/idf_tools.py --non-interactive install cmake
        ./install.sh
        source ./export.sh
        cd $GITHUB_WORKSPACE/$PROJECT_PATH
        idf.py build
        cd build
        esptool.py --chip ESP32-S3 merge_bin -o $BIN_FILE @flash_args
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: factory-firmware_IDF5.0
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          examples/factory_demo/build/ESP-*.bin
        retention-days: 90
